# Generated by Django 4.2.6 on 2023-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('nickname', models.CharField(max_length=50, verbose_name='Кличка')),
                ('age', models.PositiveIntegerField(null=True, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
