# Generated by Django 4.2.6 on 2023-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='Цена'),
        ),
    ]
